### ISSUE TITLE
Multires pano on windows

### ISSUE THREAD

**Issue by PaulKsi** [mpetroff/pannellum#1111]
All i get is cubic.pto file and thats it not sure how to fix it, can anybody tell what kind of versions of all pip installs works on windows? thanks

C:\pano-multi>python generate.py -n C:\ProgramFiles\Hugin\bin\nona.exe pano-image.jpg
Processing input image information...
Assuming --haov 360.0
Assuming --vaov 180.0
Generating cube faces...
Traceback (most recent call last):
  File "C:\pano-multi\generate.py", line 239, in <module>
    subprocess.check_call([args.nona, ('-g' if args.gpu else '-d') , '-o', os.path.join(args.output, 'face'), os.path.join(args.output, 'cubic.pto')])
  File "C:\Users\Paul Ksi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Paul Ksi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Paul Ksi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Paul Ksi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by PaulKsi** [comment]
yes, nona and hugin are installed

**Comment by mpetroff** [comment]
You're providing an invalid path to nona. I assume you meant to type `"C:\Program Files\Hugin\bin\nona.exe"` (`C:\ProgramFiles`, without a space, isn't a directory, and you need to quote the path once you add the missing space).

**Comment by PaulKsi** [comment]
> You're providing an invalid path to nona. I assume you meant to type `"C:\Program Files\Hugin\bin\nona.exe"` (`C:\ProgramFiles`, without a space, isn't a directory, and you need to quote the path once you add the missing space).

Thank you!
