### ISSUE TITLE
Intermittent issue saying image cannot be accessed

### ISSUE THREAD

**Issue by fareed945** [mpetroff/pannellum#1134]
I'm facing few intermittent issues while loading image.
![image (2)](https://user-images.githubusercontent.com/64576027/207884492-8c243bc8-564b-4e65-9758-bb21667f0b34.png)
It happens at random occasions.  The only difference is that i'm using the pannellum source code from my assets instead of npm install.
Please help

**Comment by fareed945** [comment]
This is the error stack

TypeError: Failed to execute 'readAsBinaryString' on 'FileReader': parameter 1 is not of type 'Blob'.
    at _global.<computed>.<computed> [as readAsBinaryString] (zone.js:924:1)
    at Fa (pannellum.js:66:95)
    at fa.onloadend [as __zone_symbol__ON_PROPERTYloadend] (pannellum.js:58:86)
    at XMLHttpRequest.wrapFn (zone.js:766:1)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25579:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:1)
    at invokeTask (zone.js:1661:1)

**Comment by mpetroff** [comment]
The stack trace is not what you need. A CORS error should show up as a warning in the console, and would definitely show up in the network tab.

**Comment by fareed945** [comment]
So, you mean to say that this might be an issue with the handshake between browser and the cloud storage ?

**Comment by mpetroff** [comment]
The problem is likely that you're accessing an image on a different domain than where you're hosting the viewer, and your CORS headers are incorrect. It's a HTTP header issue.

**Comment by fareed945** [comment]
@mpetroff Thanks for the info, any reason that you can think of as to why it occurs intermittently and not always?

**Comment by mpetroff** [comment]
It could happen due to caching. For example, if you first load the image by directly visiting the URL, the request won't include CORS headers. If you then try to load the image from Pannellum, your browser will just use the cached copy, which doesn't include CORS headers, so the panorama will fail to load.

There could be other reasons related to your server configuration, but that's the reason I'm most familiar with.

The way to avoid this is to host your images on the same domain as the page that you display your panoramas on if you're using Pannellum's API or to host `pannellum.htm` on the same domain as your images if you're using the standalone `<iframe>` embed version.

**Comment by fareed945** [comment]
Thanks for your reply, let me sum it up:
I have an angular app hosted on a domain let's say xyz.com,  I have my pannellum.js, .htm and the .css files in my assets of the angular app.
My images are hosted on azure blob, which allow CORS with **Access-Control-Allow-Origin: ***, since this issue is occurring intermittently and nor does it show any warning in the console/network tab related to CORS .

Do you think it could be an issue with loading these files from the assets ?, should they be hosted somewhere else ?

**Comment by mpetroff** [comment]
> nor does it show any warning in the console/network tab related to CORS

The headers for the request in the network tab either will or will not include CORS headers. It will definitely tell you something.

I still suspect your issue may be caching related.
