### ISSUE TITLE
(build) FileNotFoundError

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#457]
When trying to build from latest master ('build.py' or 'build.sh'), I get the following error:
````
========================================
Compiling pannellum.js
========================================
========================================
Compiling pannellum.css
========================================
========================================
Compiling pannellum.htm
========================================
Traceback (most recent call last):
File "build.py", line 152, in <module>
main()
File "build.py", line 149, in main
build(JS, CSS, HTML, 'pannellum')
File "build.py", line 141, in build
output(addHeaderHTML(html, version), folder + htmlfilename)
File "build.py", line 35, in output
with open(os.path.join('../..', 'build', filename), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../build/pannellum.htm'
````
Working directory is './utils/build'. - It worked correctly in the past.

**Comment by strarsis** [comment]
After checking out with git again, building worked. Maybe it was a line ending related issue?
