### ISSUE TITLE
Error prozeesing input image information multires pictures for pannellum

### ISSUE THREAD

**Issue by djsifu77** [mpetroff/pannellum#713]
Hello,
i do not know what is wrong processing multires picture for pannellum. Last week it worked great. Today i realised that i still have a problem with this following error message.
admins-MBP:~ admin$ python /Volumes/EOS1100D/MultiRes/dll/generate.py -n /Volumes/EOS1100D/MultiRes/dll/nona.exe /Volumes/EOS1100D/MultiRes/input/Roessle_1.jpg -o /Volumes/EOS1100D/MultiRes/output/R
Processing input image information...
Assuming --haov 360.0
Assuming --vaov 180.0
Generating cube faces...
Traceback (most recent call last):
  File "/Volumes/EOS1100D/MultiRes/dll/generate.py", line 165, in <module>
    subprocess.check_call([args.nona, ('-g' if args.gpu else '-d') , '-o', os.path.join(args.output, 'face'), os.path.join(args.output, 'cubic.pto')])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

Thanks for any help

Mike

**Comment by mpetroff** [comment]
You have a broken Python / Nona install, since the `OSError` indicates that Python is unable to call `nona`. I also don't understand what you're doing, since you seem to be on a Mac but appear to be trying to use a Windows copy of Nona.

**Comment by djsifu77** [comment]
Thank you for your fast response. You are right. It is not the right way to use nona.exe on a Macintosh. I change the path from nona to the local hugin.application. Now the terminalcommand is running well.
Thank you
Mike

Mit freundlichen Grüßen
Mike Fischer
